## A.I. Assignment 5

## Learning Goals

By the end of this lab, you should be able to:
* Get more familiar with tensors in pytorch 
* Create a simple multilayer perceptron model with pytorch
* Visualise the parameters


### Task

Build a fully connected feed forward network that adds two bits. Determine the a propper achitecture for this network (what database you use for this problem? how many layers? how many neurons on each layer? what is the activation function? what is the loss function? etc)

Create at least 3 such networks and compare their performance (how accurate they are?, how farst they are trained to get at 1 accuracy?)

Display for the best one the weights for each layer.


In [39]:
import torch
import torch.nn as nn
from collections import OrderedDict


In [50]:
# your code here
model = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(2, 4)),  # hidden layer with 4 neurons
    ('sigmoid', nn.Sigmoid()),   # sigmoid activation function
    ('output', nn.Linear(4, 1)),  # output layer with 1 neuron
]))

In [51]:
print(model)

Sequential(
  (hidden): Linear(in_features=2, out_features=4, bias=True)
  (sigmoid): Sigmoid()
  (output): Linear(in_features=4, out_features=1, bias=True)
)


In [52]:
# your code here
data_in = torch.tensor([[0,0], [0,1], [1,0], [1,1]], dtype=torch.float)
print(data_in)

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])


In [53]:
# your code here
data_target = torch.tensor( [[0],[1],[1],[0]], dtype=torch.float)
print(data_target)

tensor([[0.],
        [1.],
        [1.],
        [0.]])


In [54]:
# your code here
criterion = nn.BCEWithLogitsLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

In [55]:
# your code here
# Train the model
losses = []
for epoch in range(10000):
    # reset the gradients to zero before each forward and backward pass
    optimizer.zero_grad()    
    outputs = model(data_in) # forward pass
    loss = criterion(outputs, data_target) # calculate loss
    loss.backward()          # backward pass
    optimizer.step()         # update weights
    losses.append(loss.item())
    predicted_classes = (outputs.round() == data_target)
    accuracy = predicted_classes.sum().item() / len(data_target)
    if accuracy == 1:
        print(f"Model reached 100% accuracy at epoch {epoch+1}")
        break

In [56]:
# your code here
# visualize the resuts
predicted = torch.round(outputs)
correct = (predicted == data_target).sum()
total = data_target.size(0)
accuracy = correct / total
print(f'Model Accuracy: {accuracy}%')  

Model Accuracy: 0.0%


In [57]:
# your code here
# print model wights
print(f"Model weights:")
for name, param in model1.named_parameters():
    if param.requires_grad:
        print(name, param.data)

Model weights:
hidden.weight tensor([[ 0.3701, -0.2247],
        [ 0.3572,  0.2924],
        [-0.6276, -0.4828]])
hidden.bias tensor([-0.5136, -0.2919,  0.1687])
output.weight tensor([[-0.5001,  0.4936,  0.4592],
        [ 0.0424, -0.1575,  0.0825]])
output.bias tensor([-0.0107, -0.2636])


In [48]:
import torch
import torch.nn as nn
from collections import OrderedDict
import matplotlib.pyplot as plt

model1 = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(2, 3)),  # first hidden layer with 3 neurons
    ('sigmoid', nn.Sigmoid()),    # sigmoid activation function
    ('output', nn.Linear(3, 2)),  # output layer with 2 neurons
    ('sigmoid', nn.Sigmoid())     # sigmoid activation function
]))
print(model1)

data_in1 = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float)
print(data_in1)

data_target1 = torch.tensor([[0, 0], [0, 1], [0, 1], [1, 0]], dtype=torch.float)
print(data_target1)

criterion1 = nn.MSELoss()
optimizer1 = torch.optim.SGD(model1.parameters(), lr=0.1)

# train the model
losses1 = []
for epoch in range(10000):
    # reset the gradients to zero before each forward and backward pass
    optimizer1.zero_grad()  
    # forward pass
    outputs1 = model1(data_in1)
    # calculate loss
    loss1 = criterion1(outputs1, data_target1)
    # backward pass
    loss1.backward()          
    # update weights
    optimizer1.step()         
    losses1.append(loss1.item())
    
    # accuracy
    predicted_classes1 = (outputs1.round() == data_target1)
    accuracy1 = predicted_classes1.sum().item() / len(data_target1)
    if accuracy1 == 1:
        print(f"Model 1 reached 100% accuracy at epoch {epoch+1}")
        break
        
        
# visualize the resuts
predicted = torch.round(outputs1)
correct = (predicted == data_target1).sum()
total = data_target1.size(0)
accuracy = correct / total
print(f'Model Accuracy: {accuracy}%')  

    
# print model wights
print(f"Model weights:")
for name, param in model1.named_parameters():
    if param.requires_grad:
        print(name, param.data)

Sequential(
  (hidden): Linear(in_features=2, out_features=3, bias=True)
  (sigmoid): Sigmoid()
  (output): Linear(in_features=3, out_features=2, bias=True)
)
tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])
Model 1 reached 100% accuracy at epoch 14
Model Accuracy: 1.0%
Model weights:
hidden.weight tensor([[-0.1526, -0.1048],
        [ 0.6912, -0.4462],
        [-0.6529, -0.2179]])
hidden.bias tensor([0.6511, 0.2951, 0.4255])
output.weight tensor([[ 0.1619,  0.3855, -0.3148],
        [ 0.4726,  0.1368,  0.1076]])
output.bias tensor([0.0590, 0.0538])


In [49]:
import torch
import torch.nn as nn
from collections import OrderedDict
import matplotlib.pyplot as plt

model1 = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(2, 3)),  # first hidden layer with 3 neurons
    ('ReLU', nn.ReLU()),          # relu activation function
    ('output', nn.Linear(3, 2)),  # output layer with 3 neurons
    ('sigmoid', nn.Sigmoid())     # sigmoid activation function
]))
print(model1)

data_in1 = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float)
print(data_in1)

data_target1 = torch.tensor([[0, 0], [0, 1], [0, 1], [1, 0]], dtype=torch.float)
print(data_target1)

criterion1 = nn.MSELoss()
optimizer1 = torch.optim.SGD(model1.parameters(), lr=0.1)

# train the model
losses1 = []
for epoch in range(1000):
    # reset the gradients to zero before each forward and backward pass
    optimizer1.zero_grad()    
    outputs1 = model1(data_in1) # forward pass
    loss1 = criterion1(outputs1, data_target1) # calculate loss
    loss1.backward()          # backward pass
    optimizer1.step()         # update weights
    losses1.append(loss1.item())
    predicted_classes1 = (outputs1.round() == data_target1)
    accuracy1 = predicted_classes1.sum().item() / len(data_target1)
    if accuracy1 == 1:
        print(f"Model 1 reached 100% accuracy at epoch {epoch+1}")
        break
        
# visualize the results
print(outputs1)
predicted = torch.round(outputs1)
correct = (predicted == data_target1).sum()
total = data_target1.size(0)
accuracy = correct / total
print(f'Model Accuracy: {accuracy}%') 

# print model wights
print(f"Model weights:")
for name, param in model1.named_parameters():
    if param.requires_grad:
        print(name, param.data)

Sequential(
  (hidden): Linear(in_features=2, out_features=3, bias=True)
  (ReLU): ReLU()
  (output): Linear(in_features=3, out_features=2, bias=True)
  (sigmoid): Sigmoid()
)
tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])
Model 1 reached 100% accuracy at epoch 70
tensor([[0.5186, 0.4375],
        [0.4990, 0.4341],
        [0.5071, 0.4315],
        [0.5428, 0.4204]], grad_fn=<SigmoidBackward0>)
Model Accuracy: 1.0%
Model weights:
hidden.weight tensor([[ 0.3701, -0.2247],
        [ 0.3572,  0.2924],
        [-0.6276, -0.4828]])
hidden.bias tensor([-0.5136, -0.2919,  0.1687])
output.weight tensor([[-0.5001,  0.4936,  0.4592],
        [ 0.0424, -0.1575,  0.0825]])
output.bias tensor([-0.0107, -0.2636])
